<definitions name="reviewManagement"
    targetNamespace="http://delivery.com/reviewManagement.wsdl"
    xmlns:tns="http://delivery.com/reviewManagement.wsdl"
    xmlns:xsdl="http://delivery.com/reviewManagement.wsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:http="http://schemas.xmlsoap.org/soap/"
>

<message name="createReviewInput">
    <part name ="body" element="xsdl:createReviewRequest"/>
</message>

<message name="createReviewOutput">
    <part name ="body" element="xsdl:createReviewResponse"/>
</message>

<message name="updateReviewInput">
    <part name ="body" element="xsdl:updateReviewRequest"/>
</message>

<message name="updateReviewOutput">
    <part name ="body" element="xsdl:updateReviewResponse"/>
</message>

<message name="deleteReviewInput">
    <part name ="body" element="xsdl:deleteReviewRequest"/>
</message>

<message name="deleteReviewOutput">
    <part name ="body" element="xsdl:deleteReviewResponse"/>
</message>

<message name="automaticReviewCheckingInput">
    <part name ="body" element="xsdl:automaticReviewCheckingRequest"/>
</message>

<message name="automaticReviewCheckingOutput">
    <part name ="body" element="xsdl:automaticReviewCheckingResponse"/>
</message>

<message name="createDriverReviewInput">
    <part name ="body" element="xsdl:createDriverReviewRequest"/>
</message>

<message name="createDriverReviewOutput">
    <part name ="body" element="xsdl:createDriverReviewResponse"/>
</message>

<message name="getStoreReviewInput">
    <part name ="body" element="xsdl:getStoreReviewRequest"/>
</message>

<message name="getStoreReviewOutput">
    <part name ="body" element="xsdl:getStoreReviewResponse"/>
</message>

<message name="getDriverReviewInput">
    <part name ="body" element="xsdl:getDriverReviewRequest"/>
</message>

<message name="getDriverReviewOutput">
    <part name ="body" element="xsdl:getDriverReviewResponse"/>
</message>

<portType name ="reviewManagementPortType">
    <operation name="createReview">
        <input message="tns:createReviewInput" />
        <output message="tns:createReviewOutput" />
    </operation>

    <operation name="updateReview">
        <input message="tns:updateReviewInput" />
        <output message="tns:updateReviewOutput" />
    </operation>

    <operation name="deleteReview">
        <input message="tns:deleteReviewInput" />
        <output message="tns:deleteReviewOutput" />
    </operation>

    <operation name="automaticReviewChecking">
        <input message="tns:automaticReviewCheckingInput" />
        <output message="tns:automaticReviewCheckingOutput" />
    </operation>

    <operation name="createDriverReview">
        <input message="tns:createDriverReviewInput" />
        <output message="tns:createReviewOutput" />
    </operation>

    <operation name="getStoreReview">
        <input message="tns:getStoreReviewInput" />
        <output message="tns:getStoreReviewOutput" />
    </operation>

    <operation name="getDriverReview">
        <input message="tns:getDriverReviewInput" />
        <output message="tns:getDriverReviewOutput" />
    </operation>
</portType>

<binding name="reviewManagementSoapBinding" type="tns:reviewManagementPortType">
    <soap:binding 
            style="document"
            transport="http://schemas.xmlsoap.org/soap/http"
    />

    <!-- 
        Operation 1: createReview
        ใช้ในการสร้างรีวิวของร้านอาหารขึ้นมาใหม่ โดยจะใช้ข้อมูล storeId, userId, storeComment และ storeRating
        เพื่อสร้างรีวิวใหม่ ซึ่งจะได้ออกมาเป็น status ว่า success หรือ fail 
    -->
    <operation name="createReview">
            <soap:opration soapAction="http://delivery.com/createReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 2: updateReview
        ใช้ในการใช้ในการแก้ไข (อัพเดท) รีวิวร้านอาหารที่เคยถูกเขียนไปแล้ว เช่น ต้องการแก้ไขรีวิวเนื่องจากสะกดผิดเยอะ
        ซึ่งจะมี input เป็น reviewId, userId, storeRating, storeComment โดยจะมีการเช็คว่า userId เป็นเจ้าของ
        reviewId นั้นจริงหรือไม่ เพื่อป้องกันความผิดพลาด และส่งผลลัพธ์ออกเป็น updateStatus
    -->
    <operation name="updateReview">
            <soap:opration soapAction="http://delivery.com/updateReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 3: deleteReview
        ใช้ในการใช้ในการลบรีวิวร้านอาหารในระบบหากไม่ต้องการให้แสดงรีวิวนั้น ๆ แล้ว เช่น ลบรีวิวของร้านอาหาร เป็นต้น
        โดยต้องใช้ reviewId และ userId เพื่อเช็คว่าเป็นบุคคุลเดียวกับที่เขียนรีวิวหรือไม่ก่อนลบ เพื่อป้องกันความผิดพลาดที่อาจเกิดขึ้น
    -->
    <operation name="deleteReview">
            <soap:opration soapAction="http://delivery.com/deleteReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 4: automaticReviewChecking
        ใช้สำหรับตรวจสอบคอมเมนท์รีวิวว่ามีความหยาบคายเกินเหตุหรือไม่ เพื่อป้องกันมิให้เกิดการกลั่นแกล้งหรือดูถูกกันเกิดขึ้น
        โดยหากตรวจสอบแล้วว่าผ่านจะได้ output เป็น pass หากไม่ผ่านจะได้เป็น needRevision
    -->
    <operation name="automaticReviewChecking">
            <soap:opration soapAction="http://delivery.com/automaticReviewChecking" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 5: createDriverReview
        ใช้ในการเพิ่ม rating ของ driver ที่นำอาหารมาส่ง โดยจะสามารถเพิ่มได้เป็นคะแนน 1-5 เท่านั้น
        ไม่สามารถเขียนคอมเมนท์ให้กับ driver ได้
    -->
    <operation name="createDriverReview">
            <soap:opration soapAction="http://delivery.com/createDriverReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 6: getStoreReview
        มีการเรียกใช้ storeId เพื่อตรวจสอบความคิดเห็น และคะแนนของแต่ละร้านอาหาร โดยสามารถดูคะแนนรวม
        และรายละเอียดของรีวิวได้ ไม่ว่าจะเป็นคะแนนและคอมเมนท์ที่แต่ละ user ให้ หรือ timestamp ของรีวิวนั้น ๆ 
    -->
    <operation name="getStoreReview">
            <soap:opration soapAction="http://delivery.com/getStoreReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

    <!-- 
        Operation 7: getDriverReview
        ใช้ driverId เพื่อตรวจสอบข้อมูล rating ของคนขับตาม driverId เป็นคะแนนเฉลี่ยที่ได้ทั้งหมด
    -->
    <operation name="getDriverReview">
            <soap:opration soapAction="http://delivery.com/getDriverReview" />
            <input> 
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
    </operation>

</binding>

<service name="reviewManagementService">
    <documentation>Review Management Service</documentation>
        <port name="reviewManagementPort" binding="tns:reviewManagementSoapBinding">
            <soap:address location="http://delivery.com/reviewManagementService" />
        </port>
</service>

</definitions>